"""add_mythos_hypothesis_provenance_tables

Revision ID: 860281fd287e
Revises: 001
Create Date: 2026-05-31 03:38:24.797041

Adds Mythos research loop tables:
- hypotheses: hypothesis classes generated by ResearchLoop
- tool_invocations: records of tool invocations per hypothesis
- provenance_links: end-to-end provenance chains (finding -> hypothesis -> tool -> invocation)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860281fd287e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create hypotheses table
    op.create_table(
        'hypotheses',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('engagement_id', sa.String(36), sa.ForeignKey('engagements.id'), nullable=False),
        sa.Column('hypothesis_class', sa.String(100), nullable=False, index=True),
        sa.Column('source', sa.String(20), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True, server_default='0.5'),
        sa.Column('status', sa.String(20), nullable=True, server_default='pending'),
        sa.Column('attack_category', sa.String(100), nullable=False),
        sa.Column('parent_hypothesis_id', sa.String(36), sa.ForeignKey('hypotheses.id'), nullable=True),
        sa.Column('required_capabilities', sa.JSON(), nullable=True, server_default='[]'),
        sa.Column('falsification_criteria', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    # Create tool_invocations table
    op.create_table(
        'tool_invocations',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('engagement_id', sa.String(36), sa.ForeignKey('engagements.id'), nullable=False),
        sa.Column('hypothesis_id', sa.String(36), sa.ForeignKey('hypotheses.id'), nullable=False),
        sa.Column('tool_name', sa.String(100), nullable=False),
        sa.Column('capability_tags', sa.JSON(), nullable=True, server_default='[]'),
        sa.Column('target', sa.Text(), nullable=False),
        sa.Column('params', sa.JSON(), nullable=True, server_default='{}'),
        sa.Column('result_summary', sa.JSON(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Create provenance_links table
    op.create_table(
        'provenance_links',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('finding_id', sa.String(36), sa.ForeignKey('findings.id'), nullable=False),
        sa.Column('hypothesis_id', sa.String(36), sa.ForeignKey('hypotheses.id'), nullable=False),
        sa.Column('tool_invocation_id', sa.String(36), sa.ForeignKey('tool_invocations.id'), nullable=False),
        sa.Column('tool_name', sa.String(100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Add composite index for efficient provenance chain queries
    op.create_index(
        'ix_provenance_chain',
        'provenance_links',
        ['finding_id', 'hypothesis_id', 'tool_invocation_id'],
    )

    # Add finding_metadata column to findings table if it doesn't exist
    # (for informal provenance tracking — hypothesis context in findings)
    op.alter_column('findings', 'finding_metadata',
                    existing_type=sa.JSON(),
                    existing_nullable=True,
                    new_column_name='finding_metadata')


def downgrade() -> None:
    # Remove composite index
    op.drop_index('ix_provenance_chain', table_name='provenance_links')

    # Drop tables in reverse order (respecting FK constraints)
    op.drop_table('provenance_links')
    op.drop_table('tool_invocations')
    op.drop_table('hypotheses')