"""SQLAlchemy ORM models for Assurix."""

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from sqlalchemy import JSON, Boolean, DateTime, Float, ForeignKey, Index, Integer, String, Text, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base class for all ORM models."""


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class TargetType(StrEnum):
    WEBAPP = "webapp"
    API = "api"
    CODEBASE = "codebase"


class EngagementStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    RESEARCHING = "researching"  # Mythos: hypothesis-driven research active
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class HypothesisSource(StrEnum):
    """Source of a hypothesis class."""
    PATTERN_MATCH = "pattern_match"
    LLM_GENERATED = "llm_generated"


class HypothesisStatus(StrEnum):
    """Status of a hypothesis during the research loop (8-state, plan §3.1.1).

    The 4-state enum from v1 (PENDING/INVESTIGATING/CONFIRMED/FALSIFIED) is
    replaced by the 8-state lifecycle from src/reasoning/state_machine.py.
    A destructive alembic migration (alembic/versions/2026-07-01_assurix_v2_
    architecture.py) backs this change with a 4->8 value remap.

    Mappings for the destructive migration (4 -> 8):
        PENDING            -> CANDIDATE
        INVESTIGATING      -> NEEDS_CORROBORATION
        CONFIRMED          -> VALIDATED
        FALSIFIED          -> REJECTED

    Per plan §3.1.1 (BL-5): a fall-back to the 2-state pattern (CANDIDATE
    -> VALIDATED in one step) is FORBIDDEN and is asserted-illegal by the
    HypothesisStateMachine.transit() call.
    """
    UNKNOWN = "unknown"
    CANDIDATE = "candidate"
    NEEDS_CORROBORATION = "needs_corroboration"
    NEEDS_SAFE_VALIDATION = "needs_safe_validation"
    VALIDATED = "validated"
    REJECTED = "rejected"
    OUT_OF_SCOPE = "out_of_scope"
    SUPERSEDED = "superseded"


class Hypothesis(Base):
    """A hypothesis class generated by the ResearchLoop for investigation.

    Hypotheses are the core unit of work in the Mythos architecture.
    Each hypothesis represents a class of vulnerabilities to investigate,
    generated from pattern matching (VulnerabilityPatternLibrary) or LLM creativity.
    """
    __tablename__ = "hypotheses"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str] = mapped_column(ForeignKey("engagements.id"), nullable=False)
    hypothesis_class: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    source: Mapped[HypothesisSource] = mapped_column(String(20), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=0.5)
    status: Mapped[HypothesisStatus] = mapped_column(String(20), default=HypothesisStatus.UNKNOWN)
    attack_category: Mapped[str] = mapped_column(String(100), nullable=False)
    # Parent hypothesis for refinement lineage (null = top-level)
    parent_hypothesis_id: Mapped[str | None] = mapped_column(ForeignKey("hypotheses.id"), nullable=True)
    # Capability tags needed to investigate this hypothesis (e.g., ["xss", "injection"])
    required_capabilities: Mapped[list] = mapped_column(JSON, default=list)
    # What constitutes falsification for this hypothesis
    falsification_criteria: Mapped[str] = mapped_column(Text, nullable=True)
    # Plan §3.1.1 (BL-5): the full transition chain as a JSON array of
    # {from_state, to_state, evidence_hash, timestamp, reason} objects.
    # The HypothesisStateMachine.transit() call appends to this list and
    # raises IllegalTransition for any non-allowed transition.
    state_transitions: Mapped[list] = mapped_column(JSON, default=list)
    # Content-addressed sha256 of the evidence blob backing the most recent
    # transition. Immutable: the evidence_blobs table stores the actual
    # request/response, this column is the lookup key.
    evidence_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # Plan §3.1.1: confidence is decayed on each transition. The current
    # value reflects the cumulative effect of all transitions to date.
    confidence_decay: Mapped[float] = mapped_column(Float, default=0.5)
    # Timestamp of the most recent state transition (for query/sort).
    last_transition_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC)
    )

    # Relationships (string annotations for forward references)
    engagement: Mapped["Engagement"] = relationship("Engagement", back_populates="hypotheses")
    parent_hypothesis: Mapped["Hypothesis | None"] = relationship("Hypothesis", remote_side=[id])
    provenance_links: Mapped[list["ProvenanceLink"]] = relationship("ProvenanceLink", back_populates="hypothesis")
    tool_invocations: Mapped[list["ToolInvocation"]] = relationship("ToolInvocation", back_populates="hypothesis")


class ToolInvocation(Base):
    """Records each tool invocation within the research loop.

    Links a hypothesis to the specific tool that was used to investigate it,
    enabling end-to-end provenance from finding to hypothesis to tool."""
    __tablename__ = "tool_invocations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str] = mapped_column(ForeignKey("engagements.id"), nullable=False)
    hypothesis_id: Mapped[str] = mapped_column(ForeignKey("hypotheses.id"), nullable=False)
    tool_name: Mapped[str] = mapped_column(String(100), nullable=False)
    # Capability tags used to select this tool (e.g., ["xss", "injection"])
    capability_tags: Mapped[list] = mapped_column(JSON, default=list)
    target: Mapped[str] = mapped_column(Text, nullable=False)
    params: Mapped[dict] = mapped_column(JSON, default=dict)
    result_summary: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    # Relationships (string annotations for forward references)
    engagement: Mapped["Engagement"] = relationship("Engagement", back_populates="tool_invocations")
    hypothesis: Mapped["Hypothesis"] = relationship("Hypothesis", back_populates="tool_invocations")
    provenance_links: Mapped[list["ProvenanceLink"]] = relationship("ProvenanceLink", back_populates="tool_invocation")


class ProvenanceLink(Base):
    """Links a finding to its hypothesis, tool invocation, and tool.

    Enables end-to-end provenance tracing: finding -> hypothesis -> tool invocation -> tool.
    Required for the Mythos evidence bar: every confirmed finding must have a complete chain.

    Note (Phase 2): hypothesis_id and tool_invocation_id are now nullable so that
    standard-pipeline findings (no hypothesis context) can still carry provenance
    via the tool_name field. When both are null, tool_name holds the agent name
    (e.g. "pentester").
    """
    __tablename__ = "provenance_links"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    finding_id: Mapped[str] = mapped_column(ForeignKey("findings.id"), nullable=False)
    # Nullable: standard pipeline findings have no hypothesis context.
    hypothesis_id: Mapped[str | None] = mapped_column(
        ForeignKey("hypotheses.id"), nullable=True
    )
    # Nullable: standard pipeline findings have no tool invocation record.
    tool_invocation_id: Mapped[str | None] = mapped_column(
        ForeignKey("tool_invocations.id"), nullable=True
    )
    tool_name: Mapped[str] = mapped_column(String(100), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    # Relationships (string annotations for forward references)
    finding: Mapped["Finding"] = relationship("Finding", back_populates="provenance_links")
    hypothesis: Mapped["Hypothesis"] = relationship("Hypothesis", back_populates="provenance_links")
    tool_invocation: Mapped["ToolInvocation"] = relationship("ToolInvocation", back_populates="provenance_links")

    # Composite index for efficient chain queries
    __table_args__ = (
        Index("ix_provenance_chain", "finding_id", "hypothesis_id", "tool_invocation_id"),
    )


class Severity(StrEnum):
    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class JobStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    RETRYING = "retrying"


class ArtifactType(StrEnum):
    SCREENSHOT = "screenshot"
    HAR = "har"
    REQUEST_RESPONSE = "request_response"
    TRACE = "trace"
    DOM_SNAPSHOT = "dom_snapshot"
    SEMGREP_OUTPUT = "semgrep_output"


# ---------------------------------------------------------------------------
# Relational tables
# ---------------------------------------------------------------------------


class ScopePolicy(Base):
    __tablename__ = "scope_policies"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    allowed_domains: Mapped[list[str]] = mapped_column(JSON, default=list)
    rate_rps: Mapped[float] = mapped_column(Float, default=10.0)
    max_iterations: Mapped[int] = mapped_column(Integer, default=50)
    safe_mode: Mapped[bool] = mapped_column(Boolean, default=True)
    allow_destructive: Mapped[bool] = mapped_column(Boolean, default=False)
    auth_state: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )

    targets: Mapped[list["Target"]] = relationship("Target", back_populates="policy")


class Target(Base):
    __tablename__ = "targets"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    url: Mapped[str | None] = mapped_column(Text, nullable=True)
    repo_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_type: Mapped[TargetType] = mapped_column(String(20), nullable=False)
    verified: Mapped[bool] = mapped_column(Boolean, default=False)
    verification_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    policy_id: Mapped[str | None] = mapped_column(ForeignKey("scope_policies.id"), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    policy: Mapped[ScopePolicy | None] = relationship("ScopePolicy", back_populates="targets")
    engagements: Mapped[list["Engagement"]] = relationship("Engagement", back_populates="target")


class Engagement(Base):
    __tablename__ = "engagements"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    target_id: Mapped[str] = mapped_column(ForeignKey("targets.id"), nullable=False)
    status: Mapped[EngagementStatus] = mapped_column(String(20), default=EngagementStatus.PENDING)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    iteration_count: Mapped[int] = mapped_column(Integer, default=0)
    config: Mapped[dict] = mapped_column(JSON, default=dict)
    # Persisted output of the ExploitChainer (plan §3.3.1). The
    # reasoner writes this at the end of its run; the GET
    # /scans/{id}/chains endpoint reads from here. Keeping the
    # chains as a first-class column (rather than nesting them
    # inside the JSON ``config`` blob) makes the persistence
    # explicit and the read path a single ``session.refresh`` —
    # no LLM call, no graph rebuild on read.
    chains: Mapped[list] = mapped_column(JSON, default=list)
    chain_run_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    target: Mapped[Target] = relationship("Target", back_populates="engagements")
    findings: Mapped[list["Finding"]] = relationship("Finding", back_populates="engagement")
    jobs: Mapped[list["Job"]] = relationship("Job", back_populates="engagement")
    artifacts: Mapped[list["EvidenceArtifact"]] = relationship(
        "EvidenceArtifact", back_populates="engagement"
    )
    audit_logs: Mapped[list["AuditLog"]] = relationship("AuditLog", back_populates="engagement")
    hypotheses: Mapped[list["Hypothesis"]] = relationship("Hypothesis", back_populates="engagement")
    tool_invocations: Mapped[list["ToolInvocation"]] = relationship("ToolInvocation", back_populates="engagement")


class Finding(Base):
    __tablename__ = "findings"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str] = mapped_column(ForeignKey("engagements.id"), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[Severity] = mapped_column(String(20), nullable=False)
    confidence_score: Mapped[float] = mapped_column(Float, default=0.0)
    validated: Mapped[bool] = mapped_column(Boolean, default=False)
    cwe_id: Mapped[str | None] = mapped_column(String(20), nullable=True)
    owasp_category: Mapped[str | None] = mapped_column(String(50), nullable=True)
    remediation: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_agent: Mapped[str] = mapped_column(String(100), nullable=False)
    finding_metadata: Mapped[dict] = mapped_column(JSON, default=dict)
    # Stable identity used for deduplication at report time. Nullable
    # so legacy findings (pre-dedup-aware pipeline) can remain valid;
    # NULL rows are skipped by ``_deduplicate_findings()``.
    dedup_key: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    # --- v2 Verifier Triad (plan §3.2.3) ----------------------------------
    # Each finding's triadic verdict is captured as a *run id* pointing
    # at the ``verifier_runs`` row that recorded the vote. All three
    # must be non-null for a finding to reach ``validated=True`` (the
    # ``strict_finding_gate`` enforces this in the validator pipeline).
    reproducer_run_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    adversary_run_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    validator_run_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # SHA-256 of the canonical evidence blob. Set once and never
    # mutated; downstream chains key off this hash.
    evidence_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # Set True only after Validator clears scope + dedup. Drives
    # ExploitChainer's BFS in §5.4 — only chain_eligible findings
    # participate.
    chain_eligible: Mapped[bool] = mapped_column(Boolean, default=False, server_default=text("0"))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    engagement: Mapped[Engagement] = relationship("Engagement", back_populates="findings")
    artifacts: Mapped[list["EvidenceArtifact"]] = relationship(
        "EvidenceArtifact", back_populates="finding"
    )
    provenance_links: Mapped[list["ProvenanceLink"]] = relationship("ProvenanceLink", back_populates="finding")


class EvidenceArtifact(Base):
    __tablename__ = "evidence_artifacts"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str] = mapped_column(ForeignKey("engagements.id"), nullable=False)
    finding_id: Mapped[str | None] = mapped_column(ForeignKey("findings.id"), nullable=True)
    artifact_type: Mapped[ArtifactType] = mapped_column(String(50), nullable=False)
    file_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    content: Mapped[dict] = mapped_column(JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    engagement: Mapped[Engagement] = relationship("Engagement", back_populates="artifacts")
    finding: Mapped[Finding | None] = relationship("Finding", back_populates="artifacts")


class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str | None] = mapped_column(ForeignKey("engagements.id"), nullable=True)
    action: Mapped[str] = mapped_column(String(100), nullable=False)
    actor: Mapped[str] = mapped_column(String(100), nullable=False)
    payload: Mapped[dict] = mapped_column(JSON, default=dict)
    prev_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    current_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    engagement: Mapped[Engagement | None] = relationship("Engagement", back_populates="audit_logs")


class Job(Base):
    __tablename__ = "jobs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str] = mapped_column(ForeignKey("engagements.id"), nullable=False)
    agent_name: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[JobStatus] = mapped_column(String(20), default=JobStatus.QUEUED)
    priority: Mapped[int] = mapped_column(Integer, default=5)
    payload: Mapped[dict] = mapped_column(JSON, default=dict)
    result: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, default=0)
    max_retries: Mapped[int] = mapped_column(Integer, default=3)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )

    engagement: Mapped[Engagement] = relationship("Engagement", back_populates="jobs")


# ---------------------------------------------------------------------------
# Graph tables
# ---------------------------------------------------------------------------


class GraphNode(Base):
    __tablename__ = "graph_nodes"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    node_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    label: Mapped[str] = mapped_column(String(500), nullable=False)
    properties: Mapped[dict] = mapped_column(JSON, default=dict)


class GraphEdge(Base):
    __tablename__ = "graph_edges"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    engagement_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    source_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    target_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    edge_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    properties: Mapped[dict] = mapped_column(JSON, default=dict)
    # Plan §3.3.1: capability tagged on the edge. The ExploitChainer BFS
    # joins GraphEdge.capability == ChainPattern.consumes to find edges
    # that grant a capability the next pattern needs. Nullable because
    # the LLM does not always emit a capability for a "weak" edge and
    # because the runtime guard (src/graph/capabilities.py:guard_capability)
    # downgrades unknown values to NULL.
    capability: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)

# Benchmark models (imported separately to keep main models clean)
