"""Hypothesis schemas for the Mythos ResearchLoop."""

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class HypothesisSource(StrEnum):
    """Source of a hypothesis class."""
    PATTERN_MATCH = "pattern_match"
    LLM_GENERATED = "llm_generated"


class HypothesisStatus(StrEnum):
    """Status of a hypothesis during the research loop (8-state, plan §3.1.1).

    The 4-state enum from v1 (PENDING/INVESTIGATING/CONFIRMED/FALSIFIED) is
    replaced by the 8-state lifecycle from src/reasoning/state_machine.py.
    """
    UNKNOWN = "unknown"
    CANDIDATE = "candidate"
    NEEDS_CORROBORATION = "needs_corroboration"
    NEEDS_SAFE_VALIDATION = "needs_safe_validation"
    VALIDATED = "validated"
    REJECTED = "rejected"
    OUT_OF_SCOPE = "out_of_scope"
    SUPERSEDED = "superseded"


class HypothesisClass(BaseModel):
    """A hypothesis class generated by HypothesisGenerator or ReflectionPhase.

    Represents a category of vulnerabilities to investigate.
    Each hypothesis has source attribution, required capabilities for
    investigation, and falsification criteria.
    """

    hypothesis_class: str = Field(
        ...,
        description="Short kebab-case name (e.g., 'cart-price-manipulation')",
        min_length=1,
        max_length=100,
    )
    attack_category: str = Field(
        ...,
        description="One of: auth_bypass, injection, xss, csrf, ssrf, business_logic, "
                    "race_condition, idor, misconfig, data_exposure, privilege_escalation, "
                    "api_abuse, crypto_flaw",
    )
    description: str = Field(
        ...,
        description="One sentence explaining what this hypothesis investigates",
        min_length=1,
    )
    source: HypothesisSource = Field(
        ...,
        description="Whether this hypothesis came from pattern matching or LLM creativity",
    )
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Initial confidence score",
    )
    required_capabilities: list[str] = Field(
        default_factory=list,
        description="Tool capability tags needed to investigate (e.g., ['xss', 'injection'])",
    )
    falsification_criteria: str = Field(
        default="",
        description="What constitutes falsification for this hypothesis",
    )
    parent_hypothesis_class: str | None = Field(
        default=None,
        description="Parent hypothesis class if this is a refinement",
    )

    def dedup_key(self) -> str:
        """Generate a deduplication key: (attack_category, hypothesis_class)."""
        return f"{self.attack_category.lower()}:{self.hypothesis_class.lower()}"