"""Agent payload and result schemas — the core data contracts between agents."""

from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class AgentPayload(BaseModel):
    """Standard payload passed to all agents via WorkflowEngine.

    Evolved from Phase 0's observed data flows between agents.
    Each agent reads the fields it needs and ignores the rest.
    """

    engagement_id: str = Field(default_factory=lambda: str(uuid4()))
    target_url: str = ""
    iteration: int = 0
    phase: str = "initial"
    previous_result: dict[str, Any] = Field(default_factory=dict)
    surface: dict[str, Any] = Field(default_factory=dict)
    # ResearchLoop-specific fields
    hypothesis_id: str | None = None
    hypothesis_class: str | None = None
    attack_category: str | None = None
    required_capabilities: list[str] = Field(default_factory=list)
    falsification_criteria: str | None = None
    # Re-investigation support
    re_investigation: list[dict[str, Any]] | None = None


class FindingPayload(BaseModel):
    """Schema for a single finding produced by an agent.

    Every confirmed finding must have complete provenance linking
    it back to its hypothesis and tool invocation.
    """

    id: str = Field(default_factory=lambda: str(uuid4()))
    engagement_id: str
    title: str
    description: str
    severity: str  # info, low, medium, high, critical
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    validated: bool = False
    cwe_id: str | None = None
    owasp_category: str | None = None
    remediation: str | None = None
    source_agent: str
    evidence: str = ""
    # Hypothesis context for provenance
    hypothesis_class: str | None = None
    attack_category: str | None = None
    # Additional metadata
    finding_metadata: dict[str, Any] = Field(default_factory=dict)


class HypothesisPayload(BaseModel):
    """Schema for hypothesis data passed within the ResearchLoop.

    Represents a hypothesis class to investigate, generated by
    HypothesisGenerator or ReflectionPhase.
    """

    hypothesis_class: str
    attack_category: str
    description: str
    source: str  # pattern_match or llm_generated
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    required_capabilities: list[str] = Field(default_factory=list)
    falsification_criteria: str = ""
    parent_hypothesis_class: str | None = None


class AgentResult(BaseModel):
    """Standard result returned by all agents.

    Contains findings, artifacts, and optional provenance metadata.
    The ResearchLoop compiles these from all hypothesis investigations.
    """

    findings: list[dict[str, Any]] = Field(default_factory=list)
    artifacts: list[dict[str, Any]] = Field(default_factory=list)
    # ResearchLoop-specific metadata
    hypotheses_investigated: int = 0
    hypotheses_confirmed: int = 0
    hypotheses_falsified: int = 0
    total_findings: int = 0
    high_severity_findings: int = 0
    research_iterations: int = 0
    agent: str = ""
    error: str | None = None