"""Markdown security report generator with LLM-enhanced narratives."""

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


def generate_report(
    engagement_id: str,
    target_url: str,
    findings: list[dict[str, Any]],
    attack_paths: list[dict[str, Any]] | None = None,
    surface: dict[str, Any] | None = None,
    analysis_notes: str = "",
    risk_rating: str = "medium",
    artifacts_dir: Path | None = None,
    proofs_of_concept: list[dict[str, Any]] | None = None,
) -> Path:
    """Generate a structured Markdown security report.

    Returns the path to the generated report file.
    """
    if artifacts_dir is None:
        artifacts_dir = Path("./data/artifacts")
    report_dir = artifacts_dir / engagement_id
    report_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    sorted_findings = sorted(
        findings, key=lambda f: SEVERITY_ORDER.get(f.get("severity", "info"), 4)
    )

    severity_counts: dict[str, int] = {}
    for f in sorted_findings:
        sev = f.get("severity", "info")
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    lines: list[str] = [
        f"# Security Assessment Report",
        f"",
        f"**Target**: {target_url}  ",
        f"**Date**: {timestamp}  ",
        f"**Risk Rating**: {risk_rating.upper()}  ",
        f"**Engagement ID**: {engagement_id}",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
    ]

    if analysis_notes:
        lines.append(analysis_notes)
        lines.append("")

    lines.extend([
        f"### Findings Overview",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
    ])
    for sev in ["critical", "high", "medium", "low", "info"]:
        count = severity_counts.get(sev, 0)
        if count > 0:
            lines.append(f"| {sev.upper()} | {count} |")
    lines.append("")

    if surface:
        lines.extend(_format_surface(surface))

    if sorted_findings:
        lines.extend([f"## Detailed Findings", f""])
        for i, f in enumerate(sorted_findings, 1):
            lines.extend(_format_finding(i, f))

    if attack_paths:
        lines.extend([f"## Attack Paths", f""])
        for ap in attack_paths:
            lines.extend(_format_attack_path(ap))

    if proofs_of_concept:
        lines.extend([f"## Proof of Concept", f""])
        for i, poc in enumerate(proofs_of_concept, 1):
            lines.extend(_format_poc(i, poc))

    lines.extend([
        f"---",
        f"",
        f"*Report generated by Assurix Autonomous Security Validation Platform*  ",
        f"*{timestamp}*",
    ])

    report_path = report_dir / "report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Report written to %s", report_path)
    return report_path


def _format_surface(surface: dict[str, Any]) -> list[str]:
    lines: list[str] = ["## Attack Surface", ""]
    techs = surface.get("technologies", [])
    if techs:
        lines.append(f"**Technologies**: {', '.join(techs)}  ")
    pages = surface.get("pages", [])
    if pages:
        lines.append(f"**Pages discovered**: {len(pages)}  ")
    forms = surface.get("forms", [])
    if forms:
        lines.append(f"**Forms**: {len(forms)}  ")
    endpoints = surface.get("endpoints", [])
    if endpoints:
        lines.append(f"**Endpoints**: {len(endpoints)}  ")
    auth_pages = surface.get("auth_pages", [])
    if auth_pages:
        lines.append(f"**Auth pages**: {len(auth_pages)}  ")
    lines.append("")
    return lines


def _format_finding(index: int, f: dict[str, Any]) -> list[str]:
    title = f.get("title", "Unknown Finding")
    severity = f.get("severity", "info").upper()
    description = f.get("description", "")
    owasp = f.get("owasp_category", "")
    cwe = f.get("cwe_id", "")
    confidence = f.get("confidence_score", 0)
    evidence = f.get("evidence", {})
    remediation = f.get("remediation", "")
    source = f.get("source_agent", "")

    lines = [
        f"### {index}. {title}",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Severity | **{severity}** |",
    ]
    if owasp:
        lines.append(f"| OWASP | {owasp} |")
    if cwe:
        lines.append(f"| CWE | {cwe} |")
    lines.append(f"| Confidence | {confidence:.0%} |")
    if source:
        lines.append(f"| Source | {source} |")
    lines.append("")

    if description:
        lines.append(f"{description}")
        lines.append("")

    if evidence:
        lines.append("**Evidence**:")
        lines.append("```")
        for key, val in evidence.items() if isinstance(evidence, dict) else []:
            val_str = str(val)[:200]
            lines.append(f"  {key}: {val_str}")
        lines.append("```")
        lines.append("")

    if remediation:
        lines.append(f"**Remediation**: {remediation}")
        lines.append("")

    lines.append("---")
    lines.append("")
    return lines


def _format_attack_path(ap: dict[str, Any]) -> list[str]:
    name = ap.get("name", "Unnamed Attack Path")
    severity = ap.get("severity", "medium").upper()
    description = ap.get("description", "")
    steps = ap.get("steps", [])

    lines = [
        f"### {name} [{severity}]",
        "",
        f"{description}",
        "",
    ]
    if steps:
        lines.append("**Steps**:")
        for step in steps:
            lines.append(f"1. {step}")
        lines.append("")
    lines.append("---")
    lines.append("")
    return lines


def _format_poc(index: int, poc: dict[str, Any]) -> list[str]:
    title = poc.get("title", f"PoC {index}")
    poc_type = poc.get("poc_type", "unknown")
    command = poc.get("command", "")
    html_poc = poc.get("html_poc", "")
    description = poc.get("description", "")
    severity = poc.get("severity", "medium").upper()

    lines = [
        f"### {index}. {title} [{severity}]",
        "",
        f"**Type**: {poc_type}",
        "",
    ]
    if description:
        lines.append(f"{description}")
        lines.append("")
    if command:
        lines.append("**Command**:")
        lines.append("```bash")
        lines.append(command)
        lines.append("```")
        lines.append("")
    if html_poc:
        lines.append("**HTML Proof**:")
        lines.append("```html")
        lines.append(html_poc[:500])
        lines.append("```")
        lines.append("")
    lines.append("---")
    lines.append("")
    return lines