"""MD file-based memory system for AI browser agents.

Provides anti-hallucination checkpoints by writing structured findings
to markdown files. Each finding requires an evidence reference
(screenshot path, DOM snippet, or tool output) before it can be committed.
"""

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from src.agents.meta_learning import TechniqueMemory

logger = logging.getLogger(__name__)

FINDINGS_HEADER = """# Security Findings — {engagement_id}

> Auto-generated by Assurix AI Browser Agent
> Last updated: {timestamp}

"""

SURFACE_HEADER = """# Attack Surface Map — {engagement_id}

> Auto-generated by Assurix AI Browser Agent
> Last updated: {timestamp}

"""

HYPOTHESES_HEADER = """# Active Hypotheses — {engagement_id}

> Auto-generated by Assurix AI Browser Agent
> Last updated: {timestamp}

"""

INVESTIGATED_HEADER = """# Investigated Items — {engagement_id}

> Auto-generated by Assurix AI Browser Agent
> Last updated: {timestamp}

"""


class FindingMemory:
    """MD file-based memory for security findings with anti-hallucination checks.

    Each engagement gets its own memory directory under artifacts/{engagement_id}/memory/.
    """

    def __init__(self, engagement_id: str, artifacts_dir: Path) -> None:
        self._engagement_id = engagement_id
        self._memory_dir = artifacts_dir / engagement_id / "memory"
        self._memory_dir.mkdir(parents=True, exist_ok=True)
        self._findings_path = self._memory_dir / "findings.md"
        self._surface_path = self._memory_dir / "surface.md"
        self._hypotheses_path = self._memory_dir / "hypotheses.md"
        self._investigated_path = self._memory_dir / "investigated.md"
        self._findings_cache: list[dict[str, Any]] = []
        self._surface_cache: dict[str, Any] = {}
        self._hypotheses_cache: list[dict[str, Any]] = []
        self._investigated_cache: set[str] = set()

    def _timestamp(self) -> str:
        return datetime.now(UTC).isoformat()

    def _write_md(self, path: Path, content: str) -> None:
        path.write_text(content, encoding="utf-8")

    def _read_md(self, path: Path) -> str:
        if path.exists():
            return path.read_text(encoding="utf-8")
        return ""

    # --- Findings ---

    def add_finding(
        self,
        title: str,
        severity: str,
        description: str,
        evidence_ref: str,
        vuln_type: str = "unknown",
        reproduction: str = "",
        url: str = "",
    ) -> bool:
        """Add a finding with mandatory evidence reference (anti-hallucination).

        Returns False if evidence_ref is empty — findings without evidence are rejected.
        """
        if not evidence_ref or not evidence_ref.strip():
            logger.warning("Finding '%s' rejected: no evidence reference provided", title)
            return False

        dedup_key = f"{vuln_type}:{url}:{title}"
        if dedup_key in {f"{f['vuln_type']}:{f['url']}:{f['title']}" for f in self._findings_cache}:
            logger.debug("Duplicate finding skipped: %s", title)
            return False

        finding: dict[str, Any] = {
            "title": title,
            "severity": severity,
            "description": description,
            "evidence_ref": evidence_ref,
            "vuln_type": vuln_type,
            "reproduction": reproduction,
            "url": url,
            "timestamp": self._timestamp(),
        }
        self._findings_cache.append(finding)
        self._persist_findings()
        return True

    def _persist_findings(self) -> None:
        lines = [FINDINGS_HEADER.format(
            engagement_id=self._engagement_id,
            timestamp=self._timestamp(),
        )]
        for f in self._findings_cache:
            lines.append(f"## {f['title']}\n")
            lines.append(f"- **Severity**: {f['severity']}")
            lines.append(f"- **Type**: {f['vuln_type']}")
            lines.append(f"- **URL**: {f['url']}")
            lines.append(f"- **Evidence**: `{f['evidence_ref']}`")
            lines.append(f"\n{f['description']}\n")
            if f["reproduction"]:
                lines.append(f"**Reproduction**: {f['reproduction']}\n")
            lines.append("---\n")
        self._write_md(self._findings_path, "\n".join(lines))

    def get_findings(self) -> list[dict[str, Any]]:
        return list(self._findings_cache)

    # --- Surface Map ---

    def update_surface(self, section: str, data: Any) -> None:
        self._surface_cache[section] = data
        self._persist_surface()

    def _persist_surface(self) -> None:
        lines = [SURFACE_HEADER.format(
            engagement_id=self._engagement_id,
            timestamp=self._timestamp(),
        )]
        for section, data in self._surface_cache.items():
            lines.append(f"## {section}\n")
            if isinstance(data, list):
                for item in data:
                    lines.append(f"- {item}")
            elif isinstance(data, dict):
                for key, value in data.items():
                    lines.append(f"- **{key}**: {value}")
            else:
                lines.append(str(data))
            lines.append("")
        self._write_md(self._surface_path, "\n".join(lines))

    def get_surface(self) -> dict[str, Any]:
        return dict(self._surface_cache)

    # --- Hypotheses ---

    def add_hypothesis(
        self,
        title: str,
        description: str,
        vuln_type: str,
        target_url: str = "",
        priority: str = "medium",
    ) -> None:
        hypothesis: dict[str, Any] = {
            "title": title,
            "description": description,
            "vuln_type": vuln_type,
            "target_url": target_url,
            "priority": priority,
            "status": "active",
            "timestamp": self._timestamp(),
        }
        self._hypotheses_cache.append(hypothesis)
        self._persist_hypotheses()

    def resolve_hypothesis(self, title: str, status: str = "confirmed") -> None:
        for h in self._hypotheses_cache:
            if h["title"] == title:
                h["status"] = status
                break
        self._persist_hypotheses()

    def _persist_hypotheses(self) -> None:
        lines = [HYPOTHESES_HEADER.format(
            engagement_id=self._engagement_id,
            timestamp=self._timestamp(),
        )]
        for h in self._hypotheses_cache:
            lines.append(f"## {h['title']} [{h['status']}]\n")
            lines.append(f"- **Type**: {h['vuln_type']}")
            lines.append(f"- **Priority**: {h['priority']}")
            lines.append(f"- **Target**: {h['target_url']}")
            lines.append(f"\n{h['description']}\n")
            lines.append("---\n")
        self._write_md(self._hypotheses_path, "\n".join(lines))

    def get_active_hypotheses(self) -> list[dict[str, Any]]:
        return [h for h in self._hypotheses_cache if h["status"] == "active"]

    # --- Investigated Items ---

    def mark_investigated(self, item: str) -> None:
        self._investigated_cache.add(item)
        self._persist_investigated()

    def is_investigated(self, item: str) -> bool:
        return item in self._investigated_cache

    def _persist_investigated(self) -> None:
        lines = [INVESTIGATED_HEADER.format(
            engagement_id=self._engagement_id,
            timestamp=self._timestamp(),
        )]
        for item in sorted(self._investigated_cache):
            lines.append(f"- {item}")
        self._write_md(self._investigated_path, "\n".join(lines))

    # --- Context for LLM ---

    def get_context_summary(self) -> str:
        parts: list[str] = []
        if self._findings_cache:
            parts.append(f"Findings: {len(self._findings_cache)}")
            for f in self._findings_cache:
                parts.append(f"  - [{f['severity']}] {f['title']} ({f['vuln_type']})")
        if self._surface_cache:
            parts.append(f"Surface sections: {list(self._surface_cache.keys())}")
        if self._hypotheses_cache:
            active = [h for h in self._hypotheses_cache if h["status"] == "active"]
            parts.append(f"Active hypotheses: {len(active)}")
        if self._investigated_cache:
            parts.append(f"Investigated items: {len(self._investigated_cache)}")
        return "\n".join(parts) if parts else "No findings yet"
    # --- Bayesian Hypotheses (Mythos Enhancement) ---

    def add_bayesian_hypothesis(
        self,
        title: str,
        description: str,
        vuln_type: str,
        prior: float = 0.5,
        target_url: str = "",
        evidence_for: list[str] | None = None,
        evidence_against: list[str] | None = None,
    ) -> None:
        """Add a Bayesian hypothesis with prior probability."""
        hypothesis: dict[str, Any] = {
            "title": title,
            "description": description,
            "vuln_type": vuln_type,
            "target_url": target_url,
            "priority": "high" if prior > 0.7 else "medium" if prior > 0.3 else "low",
            "status": "active",
            "prior": prior,
            "posterior": prior,
            "evidence_for": evidence_for or [],
            "evidence_against": evidence_against or [],
            "updates": 0,
            "timestamp": self._timestamp(),
        }
        self._hypotheses_cache.append(hypothesis)
        self._persist_hypotheses()

    def update_hypothesis(
        self,
        title: str,
        likelihood_for: float = 0.0,
        likelihood_against: float = 0.0,
        new_evidence_for: list[str] | None = None,
        new_evidence_against: list[str] | None = None,
    ) -> dict[str, Any] | None:
        """Update a hypothesis using Bayesian inference.

        posterior = (prior * likelihood_for) / ((prior * likelihood_for) + ((1 - prior) * likelihood_against))
        """
        for h in self._hypotheses_cache:
            if h["title"] == title:
                prior = h["posterior"]
                numerator = prior * likelihood_for
                denominator = numerator + (1 - prior) * likelihood_against
                if denominator > 0:
                    h["posterior"] = numerator / denominator
                h["updates"] += 1
                if new_evidence_for:
                    h["evidence_for"].extend(new_evidence_for)
                if new_evidence_against:
                    h["evidence_against"].extend(new_evidence_against)
                # Update priority based on posterior
                if h["posterior"] > 0.7:
                    h["priority"] = "high"
                elif h["posterior"] > 0.3:
                    h["priority"] = "medium"
                else:
                    h["priority"] = "low"
                self._persist_hypotheses()
                return h
        return None

    def get_top_hypotheses(self, limit: int = 5, min_posterior: float = 0.3) -> list[dict[str, Any]]:
        """Get top hypotheses sorted by posterior probability."""
        active = [h for h in self._hypotheses_cache if h["status"] == "active" and h["posterior"] >= min_posterior]
        sorted_hypotheses = sorted(active, key=lambda h: h["posterior"], reverse=True)
        return sorted_hypotheses[:limit]

    def mark_hypothesis_failed(self, title: str, reason: str = "") -> None:
        """Mark a hypothesis as failed (disproven)."""
        for h in self._hypotheses_cache:
            if h["title"] == title:
                h["status"] = "failed"
                h["posterior"] = 0.0
                if reason:
                    h["evidence_against"].append(f"Failed: {reason}")
                break
        self._persist_hypotheses()

    # --- Action Deduplication (Mythos Enhancement) ---

    # --- Technique Memory (Phase 5: Meta-Learning) ---

    _technique_memory: "TechniqueMemory | None" = None

    def get_technique_memory(self) -> "TechniqueMemory":
        """Lazily initialise and return a TechniqueMemory instance.

        Uses the project's default database path so technique outcomes are
        persisted across engagements.
        """
        if self._technique_memory is None:
            from src.agents.meta_learning import TechniqueMemory
            self._technique_memory = TechniqueMemory()
        return self._technique_memory

    def _action_hash(self, action_type: str, url: str, params: str = "") -> str:
        """Generate a hash for action deduplication."""
        import hashlib
        key = f"{action_type}:{url}:{params}"
        return hashlib.sha256(key.encode()).hexdigest()[:16]

    def is_action_completed(self, action_type: str, url: str, params: str = "") -> bool:
        """Check if an action has already been completed (dedup)."""
        action_hash = self._action_hash(action_type, url, params)
        return action_hash in self._investigated_cache

    def mark_action_completed(self, action_type: str, url: str, params: str = "") -> None:
        """Mark an action as completed for dedup tracking."""
        action_hash = self._action_hash(action_type, url, params)
        self._investigated_cache.add(action_hash)
        # Also keep the human-readable version
        self._investigated_cache.add(f"{action_type}:{url}")
        self._persist_investigated()
